[package]
name = "dusk-cdf"
version = "0.3.0"
authors = ["Victor Lopez <victor@codx.io>"]
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/dusk-network/zkp-debugger"
readme = "README.md"
description = "PLONK debugger CDF implementation"

[dependencies]
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

[dev-dependencies]
dusk-zkp-debugger-utils = { path = "../utils" }
rand = "0.8"
tempfile = "3.3"
